language: ruby
branches:
  only: master
script: bundle exec rake deploy
env:
  global:
  - secure: Wz7Lc8riAXQcfHmpcQpzLcO0KkzzqqwBalWSWLRIUwdrSEFbUV8x2GdwKehIBr6/SAuHJ8s2JamZGuvYplGR1amZ4t3VzHETNOrTCoHo5MlkBAzwO13XXqLpyzhaFtCSrcugkhPhEEw0zxQx3ZvY2ia4tmslRHsm9QCwBEF/j3U=
  - secure: nfCoQkHh+5apSnyRW8OyypN4Kuk6fUv+2/oVCEeRwPndClKtMULgWo2CnOjaHPnIyg3kx8e922H0HcSrpv6JXBWoeZXvM1pdszrVQKLWqV9iz6nR3oZFHayCCWW8fowhabqCz/ozhaJynArKwDwcABAlJYA0maEwvCE9jghZ90g=
cache: bundler
