language: ruby
branches:
  only: master
script: bundle exec rake deploy
env:
  global:
  - secure: gKcC5AJ2zmkEk1g3+0SsreZuWE+yjh8AY8VA+CQ0oYl/D84ENvT1fFCyKf8AOdX8JJJnB90Jd2+XvlDxdLfKl001OSGjITBiG0x38uc7/Ne+Jv5ezmW/jE0B6Ow3qns4r20EiPQBhBkMOnMqLSM65yhprKmdtR/9Z4gW2Ipz3Uw=
  - secure: O3BrU/przUzxoK8aUIKl6z+8ujEKWu4iKvev6J/AnH2si0uGQrTf65cnYMVPt27tcsdz9Wi8ao0BGzHbjjG3/RfNOXzL1wlmZdBc1eCYdNuwbrE+/vaRD2mu0SQloh/W+JFt/O69sK+FesJSj13HcIXXoranq9o/9HfmG4RlADU=
cache: bundler
